name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v1
        with:
          java-version: '22'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test
