name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean install

      - name: Run tests
        run: mvn test

      # Steg för att konfigurera AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # Steg för att ladda upp till S3
      - name: Upload to S3
        run: |
          aws s3 cp target/min-spring-applikation-0.0.1-SNAPSHOT.jar s3://minspringapp-deploy-bucket/minspringapp.jar
          
           # Steg för att skapa en applikationsversion i Elastic Beanstalk
      - name: Create Elastic Beanstalk Application Version
        run: |
          aws elasticbeanstalk create-application-version --application-name minspringapp \
            --version-label ${{ github.sha }} \
            --source-bundle S3Bucket=your-app-bucket,S3Key=minspringapp.jar

      # Steg för att uppdatera Elastic Beanstalk-miljön
      - name: Update Elastic Beanstalk Environment
        run: |
          aws elasticbeanstalk update-environment --environment-name minspringapp-env \
            --version-label ${{ github.sha }}
          
